blog/urls.py
from django.urls import path
from . import views

# start with blog
urlpatterns = [
    # http://localhost:8000/blog/
    path('', views.blog_list, name='blog_list'),
    path('my_blog/', views.my_blog_list, name='my_blog_list'),
    path('<int:blog_pk>', views.blog_detail, name="blog_detail"),
    path('type/<int:blog_type_pk>', views.blogs_with_type, name="blogs_with_type"),
    path('date/<int:year>/<int:month>', views.blogs_with_date, name="blogs_with_date"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('ckeditor', include('ckeditor_uploader.urls')),
    path('blog/', include('blog.urls')),
    path('comment/', include('comment.urls')),
    path('likes/', include('likes.urls')),
    path('user/', include('user.urls')),
    path('notifications/', include('notifications.urls', namespace='notifications')),
    path('my_notifications/', include('my_notifications.urls')),
    path('todo/', include('todonow.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todonow/urls.py
from django.urls import path,include
from . import views

app_name='todonow'
urlpatterns = [

    path('home/', views.home,name='主页'),
    path('about/', views.about,name='关于'),
    path('edit/<每一件事_id>', views.edit, name='编辑'),
    path('del/<每一件事_id>', views.delete, name='删除'),
    path('cross/<每一件事_id>', views.cross,name='划掉'),
    path('timeing/<每一件事_id>', views.timeing,name='计时'),
]

todonow/models.py
from django.db import models
from django.contrib.auth.models import User
class Todo(models.Model):

    todouser = models.ForeignKey(User, on_delete=models.DO_NOTHING)  # 作者
    todothing = models.CharField(max_length=50)
    tododone = models.BooleanField(default=False)
    todoworktime = models.IntegerField(default=0)
    todogshm = models.CharField(max_length=15)

todonow/views.py
from django.shortcuts import render,redirect,HttpResponse#render渲染,redirect重定向
from .models import Todo
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required#判断是否登录
# Create your views here.


@login_required(login_url='login')#判断是否登录,如果末登陆就重定向到登录
def home(request):
    if request.method == "POST":
        if request.POST["待办事项"] == '':
            content = {"清单": Todo.objects.filter(todouser=request.user),'警告':'请输入内容!'}
            return render(request,'todonow/home.html',content)
        else:
            # request.user.username

            a_row = Todo(todouser=request.user,todothing=request.POST['待办事项'])
            a_row.save()
            content={"清单":Todo.objects.filter(todouser=request.user),'信息':'添加成功!'}
            return render(request,'todonow/home.html',content)
    elif request.method == "GET":
        #content = {"清单": Todo.objects.all()}

        content = {"清单": Todo.objects.filter(todouser=request.user)}
        print(content)
        return render(request, 'todonow/home.html', content)


def about(request):
    return render(request,'todonow/about.html')


def edit(request,每一件事_id):

    if request.method == "POST":
        if request.POST["已修改事项"] == '':
            return render(request, 'todonow/edit.html', {'警告': '请输入内容!'})
        else:
            a = Todo.objects.get(id=每一件事_id)
            a.todothing = request.POST["已修改事项"]
            a.save()
            return redirect('todonow:主页')
    elif request.method == "GET":
        a = Todo.objects.get(id=每一件事_id)
        content = {"待修改事项": a.todothing}
        return render(request,'todonow/edit.html',content)



def delete(request,每一件事_id):
    a= Todo.objects.get(id=每一件事_id)
    a.delete()
    return redirect('todonow:主页')

def cross(request,每一件事_id):
    if request.POST['完成状态']=='已完成':
        a = Todo.objects.get(id=每一件事_id)
        a.tododone=True
    else:
        a = Todo.objects.get(id=每一件事_id)
        a.tododone = False
    a.save()
    return redirect('todonow:主页')

def timeing(request,每一件事_id):

    a= Todo.objects.get(id=每一件事_id)
    b= int(request.POST['计时状态'])
    if b>1051982140862:
        b=0
    print(a.todoworktime,'+',b)
    a.todoworktime += b
    wm = a.todoworktime

    s, w = divmod(wm, 1000)
    m, s = divmod(s, 60)
    h, m = divmod(m, 60)
    a.todogshm="%02d:%02d:%02d" % (h, m, s)
    a.save()
    # 1
    return redirect('todonow:主页')

todonow/templates/todonow/DEMOC.html
<!doctype html>
<html>
    <head>
        <title>秒表</title>
        <style type="text/css"></style>
    </head>
    <body>
        <div id="div1">
            <span id="span1">00</span> :
            <span id="span2">00</span> :
            <span id="span3">00</span> :
            <span id="span4">00</span>
        </div>
        <input id="input1" type="button" value="start" onclick="whenClick();">
        <input id="input2" type="button" value="clear" onclick="clear1();">
        <script  type="text/javascript">
            var milliSeconds1 = document.getElementById("span4");
            var seconds1 = document.getElementById("span3");
            var minutes1 = document.getElementById("span2");
            var hours1 = document.getElementById("span1");
            var time=0;
            var pre_time=0;
            var intervals=0;
            var pre_intervals=0;
            var flag;

            function whenClick(){//  开始/暂停
                var inputValue = document.getElementById("input1");
                if(inputValue.value=="start"||inputValue.value=="continue"){
                    var date= new Date();
                    time = date.getTime();
                    pre_time=time;
                    inputValue.value="stop ";
                    start1();
                }
                else {
                    inputValue.value="continue";
                    stop1();
                }
            }

            function clear1(){//  清零
                stop1();
                milliSeconds1.innerHTML = seconds1.innerHTML =minutes1.innerHTML = hours1.innerHTML = "00";
                time=0;
                pre_time=0;
                intervals=0;
                pre_intervals=0;
                document.getElementById("input1").value = "start";
            }

            function start1(){//  开始/继续
                flag = setInterval("timeIncrement();",10);
            }

            function timeIncrement(){
                date = new Date();
                intervals=date.getTime()-time+pre_intervals;
                var a=intervals%1000/10;
                var b=intervals%60000/1000;
                var c=intervals%3600000/60000;
                var d=intervals/3600000;
                milliSeconds1.innerHTML=(a<10)?('0'+Math.floor(a)):(Math.floor(a));
                seconds1.innerHTML=(b<10)?('0'+Math.floor(b)):(Math.floor(b));
                minutes1.innerHTML=(c<10)?('0'+Math.floor(c)):(Math.floor(c));
                hours1.innerHTML=(d<10)?('0'+Math.floor(d)):(Math.floor(d));
            }

            function stop1(){//  暂停/停止
                date = new Date();
                pre_intervals += date.getTime()-pre_time;
                clearInterval(flag);
            }

        </script>
    </body>
</html>

todonow/templates/todonow/about.html
{% extends "todonow/base.html" %}
{% block 标题 %}关于本站{% endblock 标题 %}
{% block 关于高亮 %}active{% endblock 关于高亮 %}
{% block 主体 %}
<br>
<h4>一款小巧、简洁的待办清单工具，帮你规划日常事务。</h4>
{% endblock 主体 %}
    

todonow/templates/todonow/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>{% block 标题 %}未命名{% endblock 标题 %}</title>

    <!-- lable icon -->
    <link href="{% static 'todonow/icons/icon_list.png' %}" rel="shortcut icon" />

    <!-- Bootstrap core CSS -->
    <link href="{% static 'todonow/css/bootstrap.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'todonow/css/base.css' %}">
    <link rel="stylesheet" href="{% block css %}{% endblock css %}">
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4" id="topnav">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item {% block 主页高亮 %}{% endblock 主页高亮 %}">
            <a class="nav-link" href="{% url 'todonow:主页' %}"><img src="{% static 'todonow/images/logo_list.png' %}" width="33" height="33" class="d-inline-block align-top" alt=""> 待办清单</a>
          </li>
          <li class="nav-item {% block 关于高亮 %}{% endblock 关于高亮 %}">
            <a class="nav-link" href="{% url 'todonow:关于' %}">关于本站</a>
          </li>
          <li class="">
            <a class="nav-link" href="{% url 'home' %}">{{ user }}返回博客</a>
          </li>
        </ul>
        <form class="form-inline mt-2 mt-md-0 col-7 justify-content-end" method="POST" action="">
            {% csrf_token %}
          <input name="待办事项" class="form-control mr-sm-2" type="text" placeholder="待办事项" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">添加</button>
        </form>
      </div>
    </nav>

    <main role="main" class="container">
      {% block 主体 %}
      {% endblock 主体 %}
    </main>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster <script src="{% static 'todolist/js//popper.min.js' %}"-->
<!--
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    -->
    <script src="{% static 'todonow/js/jquery.slim.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="{% static 'todonow/js/bootstrap.js' %}"></script>

  </body>
</html>

todonow/templates/todonow/demo.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>菜鸟教程(runoob.com)</title>
<script>
function displayDate(){
	document.getElementById("demo").innerHTML="<h1>我成功了</h1>";
}
</script>
</head>
<body>

<h1>我的第一个 JavaScript 程序</h1>
<p id="demo">这是一个段落</p>

<button type="button" onclick="displayDate()">显示日期</button>

</body>
</html>

todonow/templates/todonow/edit.html
{% extends "todonow/base.html" %}
{% load static %}

{% block css %}{% static 'todonow/css/edit.css' %}{% endblock css %}

{% block 标题 %}编辑待办事项{% endblock 标题 %}
{% block 主体 %}
<br>

<form id="form-edit" method="POST" action="">
{% csrf_token %}
    {% if 警告 %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>警告!</strong> {{ 警告 }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
        </div>
    {% endif %}

  <div class="form-group">
    <label for="editTodo"></label>
    <input name="已修改事项" class="form-control form-control-lg" id="editTodo" type="text" value="{{ 待修改事项 }}">
    <small id="help" class="form-text text-muted">在这里编辑待办事项</small>
  </div>
  <button type="submit" class="btn btn-primary btn-lg btn-block">提交</button>
</form>


{% endblock 主体 %}

todonow/templates/todonow/home.html
{% extends "todonow/base.html" %}

{% load static %}

{% block css %}{% static 'todonow/css/home.css' %}{% endblock css %}

{% block 标题 %}你的个人待办清单{% endblock 标题 %}
{% block 主页高亮 %}active{% endblock 主页高亮 %}
{% block 主体 %}
<br><!--这个删掉会乱码-->
    {% if 警告 %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <strong>警告!</strong> {{ 警告 }}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %}

    {% if 信息 %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
      <strong>提示!</strong> {{ 信息 }}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %}

<div class="table-responsive">
  <table class="table table-hover">
    <thead class="thead-light">
      <tr>
        <th>序号</th>
        <th>待办事项</th>
          <th>计时</th>
          <th>用时</th>
        <th>编辑</th>
        <th>划掉</th>
        <th>删除</th>
      </tr>
    </thead>
    <tbody class="no-underline">
        {% for 每一件事 in 清单 %}
            {% ifequal user 每一件事.todouser %}
            {% if 每一件事.tododone %}
                <tr class="table-dark">
                    <th class="text-dark" scope="row">{{ forloop.counter }}</th>
                    <td class="text-dark" id="line-through">{{ 每一件事.todothing }}</td>
                    <td class="text-secondary">不可编辑</td>
                    <td>
                        <form method="POST" action="{% url 'todonow:划掉' 每一件事.id %}">
                            {% csrf_token %}
                            <input name="完成状态" type="hidden" value="末完成">
                            <button type="submit" class="btn btn-primary btn-sm">撒消</button>
                        </form>
                    </td>
                    <td>
                        <form method="POST" action="{% url 'todonow:删除' 每一件事.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger btn-sm">删除</button>
                        </form>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ 每一件事.todothing }}</td>
                    <td><!------------------------计时---------------->
                        <form method="POST" action="{% url 'todonow:计时' 每一件事.id %}">
                            {% csrf_token %}
                            <input id="input3" name="计时状态" type="hidden" value="">
                            <input id="input1{{ 每一件事.id }}" class="btn btn-default btn-sm" type="button" value="开始" onclick="whenClick({{ 每一件事.id }});">
                            <input id="input2" class="btn btn-default btn-sm" type="button" value="清空" onclick="clear1();">
                            <input id="input4" class="btn btn-default btn-sm" type="submit" value="提交" onclick="TJClick();">
                        </form>
                        <div id="{{ 每一件事.id }}">

                        </div>
                    </td>
                    <td>{{ 每一件事.todogshm }}</td>
                    <td><a class="text-info" href="{% url 'todonow:编辑' 每一件事.id %}">编辑</a></td>
                    <!--<a href="{% url 'todonow:编辑' forloop.counter %}">
                        <button type="submit" class="btn btn-primary btn-sm ">编辑</button>
                        </a>-->
                    <td>
                        <form method="POST" action="{% url 'todonow:划掉' 每一件事.id %}">
                            {% csrf_token %}
                            <input name="完成状态" type="hidden" value="已完成">
                            <button type="submit" class="btn btn-primary btn-sm">划掉</button>
                        </form>
                    </td>
                    <td>




                        <!-- Button trigger modal -->
                         <button data-toggle="modal" data-target="#exampleModal{{forloop.counter}}" type="button" class="btn btn-primary btn-sm">删除</button>

                        <!-- Modal -->
                        <div class="modal fade" id="exampleModal{{forloop.counter}}" tabindex="-1" role="dialog" aria-labelledby="exampleModal{{forloop.counter}}Label" aria-hidden="true">
                          <div class="modal-dialog" role="document">
                            <div class="modal-content">
                              <div class="modal-header">
                                <h5 class="modal-title" id="exampleModal{{forloop.counter}}Label">请确认</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                  <span aria-hidden="true">&times;</span>
                                </button>
                              </div>
                              <div class="modal-body">
                                确定要删除 <strong>未办事项 {{ 每一件事.todothing }}</strong>吗?
                              </div>
                              <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">取消</button>
                                  <form method="POST" action="{% url 'todonow:删除' 每一件事.id %}">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-primary">确定</button>
                                  </form>
                              </div>
                            </div>
                          </div>
                        </div>



                    </td>
                </tr>
            {% endif %}
            {% endifequal %}
        {% endfor %}


      <!--<tr>
        <th scope="row">2</th>
        <td>看一会小说</td>
        <td><a class="text-info" href="#">编辑</a></td>
        <td><a class="text-info" href="#">划掉</a></td>
        <td><a class="text-info" href="#">删除</a></td>
      </tr>
      <tr>
        <th scope="row">3</th>
        <td>散散步</td>
        <td><a class="text-info" href="#">编辑</a></td>
        <td><a class="text-info" href="#">划掉</a></td>
        <td><a class="text-info" href="#">删除</a></td>
      </tr>
      <tr class="table-dark">
        <th class="text-dark" scope="row">4</th>
        <td class="text-dark" id="line-through">去超市</td>
        <td class="text-secondary">不可编辑</td>
        <td><a class="text-info" href="#">撤销</a></td>
        <td><a class="text-danger" href="#">删除</a></td>
      </tr>-->
    </tbody>
  </table>

</div>




    <script  type="text/javascript">
            //var milliSeconds1 = document.getElementById("span4");
            //var seconds1 = document.getElementById("span3");
            //var minutes1 = document.getElementById("span2");
            //var hours1 = document.getElementById("span1");
            var time=0;
            var pre_time=0;
            var intervals=0;
            var pre_intervals=0;
            var flag;


            function TJClick(){//  提交
                //var inputValue3 = document.getElementById("input3");//new
                var div_ls = document.getElementsByTagName('input')

                date = new Date();
                intervals=date.getTime()-time+pre_intervals;
                var a=intervals%1000/10;
                var b=intervals%60000/1000;
                var c=intervals%3600000/60000;
                var d=intervals/3600000;

                //inputValue3.value=intervals;//new
                for(var i=0;i<div_ls.length;i++){
        	// 遍历所有的div并根据id做判断
            if(div_ls[i].getAttribute('id') == 'input3'){
            	// 对满足条件的标签设置属性即可
                div_ls[i].setAttribute('value', intervals)
            }
        }

                }


            function whenClick(id){//  开始/暂停
                var inputValue = document.getElementById("input1"+id);
                if(inputValue.value=="开始"){
                document.getElementById(id).innerHTML='<span id="span1" style="font-size:25px">00</span> : <span id="span2" style="font-size:25px">00</span> : <span id="span3" style="font-size:25px">00</span> : <span id="span4" style="font-size:25px">00</span>';
                }
                if(inputValue.value=="开始"||inputValue.value=="继续"){

                    var date= new Date();
                    time = date.getTime();
                    pre_time=time;
                    inputValue.value="停止";

                    start1();
                }
                else {
                    inputValue.value="继续";
                    stop1();
                }
            }

            function clear1(){//  清零
                stop1();
                milliSeconds1.innerHTML = seconds1.innerHTML =minutes1.innerHTML = hours1.innerHTML = "00";
                time=0;
                pre_time=0;
                intervals=0;
                pre_intervals=0;
                document.getElementById("input1").value = "开始";
            }

            function start1(){//  开始/继续
                flag = setInterval("timeIncrement();",10);
            }

            function timeIncrement(){
                date = new Date();
                intervals=date.getTime()-time+pre_intervals;
                var a=intervals%1000/10;
                var b=intervals%60000/1000;
                var c=intervals%3600000/60000;
                var d=intervals/3600000;
                document.getElementById("span4").innerHTML=(a<10)?('0'+Math.floor(a)):(Math.floor(a));
                document.getElementById("span3").innerHTML=(b<10)?('0'+Math.floor(b)):(Math.floor(b));
                document.getElementById("span2").innerHTML=(c<10)?('0'+Math.floor(c)):(Math.floor(c));
                document.getElementById("span1").innerHTML=(d<10)?('0'+Math.floor(d)):(Math.floor(d));
            }

            function stop1(){//  暂停/停止
                date = new Date();
                pre_intervals += date.getTime()-pre_time;
                clearInterval(flag);
            }

        </script>



{% endblock 主体 %}