blog/urls.py
from django.urls import path
from . import views

# start with blog
urlpatterns = [
    # http://localhost:8000/blog/
    path('', views.blog_list, name='blog_list'),
    path('my_blog/', views.my_blog_list, name='my_blog_list'),
    path('<int:blog_pk>', views.blog_detail, name="blog_detail"),
    path('type/<int:blog_type_pk>', views.blogs_with_type, name="blogs_with_type"),
    path('date/<int:year>/<int:month>', views.blogs_with_date, name="blogs_with_date"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('ckeditor', include('ckeditor_uploader.urls')),
    path('blog/', include('blog.urls')),
    path('comment/', include('comment.urls')),
    path('likes/', include('likes.urls')),
    path('user/', include('user.urls')),
    path('notifications/', include('notifications.urls', namespace='notifications')),
    path('my_notifications/', include('my_notifications.urls')),
    path('todo/', include('todonow.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todonow/urls.py
from django.urls import path,include
from . import views

app_name='todonow'
urlpatterns = [

    path('home/', views.home,name='主页'),
    path('about/', views.about,name='关于'),
    path('edit/<每一件事_id>', views.edit, name='编辑'),
    path('del/<每一件事_id>', views.delete, name='删除'),
    path('cross/<每一件事_id>', views.cross,name='划掉'),
    path('timeing/<每一件事_id>', views.timeing,name='计时'),
]

templates/base.html
{% load staticfiles %}
{% load notifications_tags %} 
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'base.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-3.3.7/css/bootstrap.min.css' %}">
    <script type="text/javascript" src="{% static 'jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap-3.3.7/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'notifications/notify.js' %}"></script>
    {% block header_extends %}{% endblock %}
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'home' %}">WOW插件同好会</a>
                <button class="navbar-toggle collapsed"  data-toggle="collapse" data-target="#navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div id="navbar-collapse" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="{% block nav_home_active %}{% endblock %}">
                        <a href="{% url 'home' %}">首页</a>
                    </li>
                    <li class="{% block nav_blog_active %}{% endblock %}">
                        <a href="{% url 'blog_list' %}">博客广场</a>
                    </li>
                    <li class="{% block nav_my_blog_active %}{% endblock %}">
                        <a href="{% url 'my_blog_list' %}">个人中心</a>
                    </li>
                    <li class="">
                        <a href="{% url 'todonow:主页' %}">待办清单</a>
                    </li>
                    <li class="">
                        <a href="{% url 'blog_list' %}">游戏</a>
                    </li>
                    <li class="">
                        <a href="/admin/blog/blog/add/">发博客</a>
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    {% if not user.is_authenticated %}
                        <li>
                            {% if request.GET.from %}
                                <a href="{% url 'login' %}?from={{ request.GET.from }}">登录</a>
                            {% else %}
                                <a href="{% url 'login' %}?from={{ request.get_full_path }}">登录</a>
                            {% endif %}
                        </li>
                        <li>
                            {% if request.GET.from %}
                                <a href="{% url 'register' %}?from={{ request.GET.from }}">注册</a>
                            {% else %}
                                <a href="{% url 'register' %}?from={{ request.get_full_path }}">注册</a>
                            {% endif %}
                        </li>
                    {% else %}
                        {% notifications_unread as unread_count %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">
                                你好，{{ user.get_nickname_or_username }}
                                <span class="badge unread-count live_notify_badge">{% if unread_count > 0 %}{{ unread_count }}{% endif %}</span>
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'user_info' %}">个人资料</a></li>
                                <li><a href="{% url 'my_notifications' %}">我的消息 <span class="badge unread-count live_notify_badge">{% if unread_count > 0 %}{{ unread_count }}{% endif %}</span></a></li>
                                {% if user.is_staff or user.is_superuser %}
                                    <li><a href="{% url 'admin:index' %}">后台管理</a></li>
                                {% endif %}
                                <li><a href="{% url 'logout' %}?from={{ request.get_full_path }}">退出</a></li>
                            </ul>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>

    {% block content %}{% endblock %}

    <!-- footer -->
    <div class="footer">
        <div class="website-info">
           <p> 反馈建议 | 官方空间 | 空间活动 | 空间应用 | ABCmouseJ版 | J原创馆 | J互联 | J登录 | 社交组件 | 应用侵权投诉 | Complaint Guidelines</p>
            <p>Copyright © 2005 - 2019 janroo.All Rights Reserved. J公司 版权所有 粤网文[1997]666-666号</p>
        </div>
    </div>

    <script type="text/javascript">
        //底部栏置底
        //窗体改变大小事件
        $(window).resize(function(){
            //正文高度
            var body_height = $(document.body).outerHeight(true);

            //底部元素高度
            var bottom_height = $("#footer").outerHeight(true);

            //浏览器页面高度
            var window_height = $(window).height();
            
            //判断并调整底部元素的样式
            if($(".footer").hasClass('page-bottom')){
                //若包含有page-bottom类，就应用了position设置
                //当position为absolute时，body高度不包含这个元素
                //所以页面高度需要判断body和footer之和若小于浏览器窗口
                //则移除样式，让footer自然跟随在正文后面
                if(body_height + bottom_height >= window_height){
                    $(".footer").removeClass('page-bottom');
                }
            }else{
                //若没有page-bottom类，body高度包含footer
                //判断body高度小于浏览器时，则悬浮于底部
                if(body_height < window_height){
                    $(".footer").addClass('page-bottom');
                }
            }
        });

        //页面加载时，模拟触发一下resize事件
        $(window).trigger('resize');

        //自定义实时获取未读消息
        function my_special_notification_callback(data){
            unread_count = data['unread_count'];
            if (unread_count == 0) {
                unread_count = '';
            }
            $('.live_notify_badge').text(unread_count);
        }
    </script>
    {% register_notify_callbacks callbacks='my_special_notification_callback' %}
    {% block script_extends %}{% endblock %}
</body>
</html>

templates/error.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    我的网站|错误
{% endblock %}

{% block nav_home_active %}active{% endblock %}

{% block content %}
    {{ message }}，<a href="{{ redirect_to }}">返回</a>
{% endblock %}

templates/form.html
{% extends 'base.html' %}

{% block title %}{{ page_title }}{% endblock %}
{% block nav_home_active %}active{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-4 col-xs-offset-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">{{ form_title }}</h3>
                    </div>
                    <div class="panel-body">
                        <form action="" method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                                {% if not field.is_hidden %}
                                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {% endif %}
                                {{ field }}
                                <p class="text-danger">{{ field.errors.as_text }}</p>
                            {% endfor %}
                            <span id="tip" class="text-danger">{{ form.non_field_errors }}</span>
                            <div class="clearfix"></div>
                            <div class="pull-left">
                                {% block other_buttons %}{% endblock %}
                            </div>
                            <div class="pull-right">
                                <input type="submit" value="{{ submit_text }}" class="btn btn-primary">
                                <button class="btn btn-default" onclick="window.location.href='{{ return_back_url }}'">返回</button>
                            </div>
                            
                        </form>
                    </div>
                </div>            
            </div>
        </div>
    </div>    
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    我的网站|首页
{% endblock %}

{% block header_extends %}
    <link rel="stylesheet" href="{% static 'home.css' %}">
    <script src="//cdn.hcharts.cn/highcharts/highcharts.js"></script>
{% endblock %}

{% block nav_home_active %}active{% endblock %}

{% block content %}
    <h3 class="home-content">欢迎访问WOW插件同好会</h3>
    <!-- 图表容器 DOM -->
    <div id="container"></div>
    <div class="hot-data">
        <h3>今天热门博客</h3>
        <ul>
            {% for hot_data in today_hot_data %}
                <li><a href="{% url 'blog_detail' hot_data.content_object.pk %}">{{ hot_data.content_object.title }}</a>({{ hot_data.read_num }})</li>            
            {% empty %}
                <li>今天暂时没有热门博客</li>
            {% endfor %}
        </ul>
    </div>
    <div class="hot-data">
        <h3>昨天热门博客</h3>
        <ul>
            {% for hot_data in yesterday_hot_data %}
                <li><a href="{% url 'blog_detail' hot_data.content_object.pk %}">{{ hot_data.content_object.title }}</a>({{ hot_data.read_num }})</li>            
            {% empty %}
                <li>昨天暂时没有热门博客</li>
            {% endfor %}
        </ul>
    </div>
    <div class="hot-data">
        <h3>7天热门博客</h3>
        <ul>
            {% for hot_blog in hot_blogs_for_7_days %}
                <li><a href="{% url 'blog_detail' hot_blog.id %}">{{ hot_blog.title }}</a>({{ hot_blog.read_num_sum }})</li>            
            {% empty %}
                <li>昨天暂时没有热门博客</li>
            {% endfor %}
        </ul>
    </div>
    <script>
        // 图表配置
        var options = {
            chart: { type: 'line' },
            title: { text: null },
            xAxis: {
                categories: {{ dates|safe }},   // x 轴分类
                tickmarkPlacement: 'on',
                title: { text: '前7日阅读量变化'},
            },
            yAxis: {
                title: { text: null },
                labels:{ enabled: false },
                gridLineDashStyle: 'Dash',
            },
            series: [{                              // 数据列
                name: '阅读量',                     // 数据列名
                data: {{ read_nums }}               // 数据
            }],
            plotOptions: {
                line: {
                    dataLabels: {
                        enabled: true
                    }
                }
            },
            legend: { enabled: false },
            credits: { enabled: false },
        };
        // 图表初始化函数
        var chart = Highcharts.chart('container', options);
    </script>
{% endblock %}